DROP TABLE IF EXISTS NoteOwner CASCADE;
DROP TABLE IF EXISTS Note CASCADE;
DROP TABLE IF EXISTS NoteViewer CASCADE;
DROP TABLE IF EXISTS Label CASCADE;
DROP TABLE IF EXISTS NoteLabel CASCADE;
DROP TABLE IF EXISTS Priority CASCADE;
-- Lisää DROP TABLE lauseet tähän tiedostoon
